name: Makefile CI
description: Build the executable by g++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile_performance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: Building performance tests with g++ (do not execute them)
      shell: bash
      run: |
        make -j 3 perf

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: Version of g++
      shell: bash
      run: g++ -v
    - name: Building unit tests with g++ and execute them
      shell: bash
      run: |
        make -j 3 unit
        ./tests/build/unit/unit_tests

