name: Makefile CI
description: Build the executable by g++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile_all_and_run_unit_test:
    name: Compile all and run unit tets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: Install Intel Thread Building Block (TBB)
      shell: bash
      run: |
        sudo apt update
        sudo apt install libtbb-dev
    - name: Version of g++
      shell: bash
      run: g++ -v
    - name: Building executables
      shell: bash
      run: make -j 4 all
    - name: Run unit tests
      shell: bash
      run: make run-unit

