name: Linux build and unit tests (Makefile) 👷
description: Build the executable by g++

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compile_all_and_run_unit_test:
    name: Compile all and run unit tets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd    # v6.0.2
    - name: Install Intel Thread Building Block (TBB)
      shell: bash
      run: |
        sudo apt update
        sudo apt install libtbb-dev
    - name: Version of g++
      shell: bash
      run: g++ -v
    - name: ⚒️ Building executables
      shell: bash
      run: make -j 4 all
    - name: 🧪 Run unit tests
      shell: bash
      run: make run-unit

  run_gunit_tests:
    name: 🧪 Google unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd    # v6.0.2
    - name: ⚒️ Building
      shell: bash
      run: |
        mkdir build
        cd build || false
        cmake ../unit_tests
        cmake --build . --parallel=4
    - name: 🧪 Run unit tests
      shell: bash
      run: |
        cd build || false
        ./run_unit_tests

  run_gunit_tests_parallel:
    name: 🧪 Google unit tests for PARALLEL
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd    # v6.0.2
    - name: Install TBB
      run: |
        sudo apt-get update
        sudo apt-get install -y libtbb-dev
    - name: ⚒️ Building
      shell: bash
      run: |
        mkdir build
        cd build || false
        cmake ../unit_tests -DPARALLEL=ON
        cmake --build . --parallel=4
    - name: 🧪 Run unit tests with PARALLEL
      shell: bash
      run: |
        cd build || false
        ./run_unit_tests
