name: Linux build and unit tests (Makefile) 👷
description: Build the executable by g++

on:
  pull_request:
    branches: [ "main" ]
  push:

jobs:
  compile_all_and_run_unit_test:
    name: Compile all and run unit tets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: Install Intel Thread Building Block (TBB)
      shell: bash
      run: |
        sudo apt update
        sudo apt install libtbb-dev
    - name: Version of g++
      shell: bash
      run: g++ -v
    - name: ⚒️ Building executables
      shell: bash
      run: make -j 4 all
    - name: 🧪 Run unit tests
      shell: bash
      run: make run-unit

  run_unit_tests:
    name: 🧪 Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: ⚒️ Building
      shell: bash
      run: |
        mkdir build
        cd build || false
        cmake ../unit_tests
        cmake --build .
    - name: 🧪 Run unit tests
      shell: bash
      run: |
        cd build || false
        ./run_unit_tests

  unit_tests_in_solution:
    runs-on: ubuntu-latest
    steps:
    - name: 👀 Test if unit tests in solution
      shell: bash
      run: |
        set -e
        cd unit_tests || false
        for cpp_file in *.cpp; do
          echo "Checking $cpp_file..."
          grep -q "\"${cpp_file}\"" unit_tests.vcxproj
        done

  all_files_in_solution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: 👀 all files in solution
      shell: bash
      run: |
        set -e
        for file in $(find la tests -type f);
          do win_file=$(echo ${file} | sed -re 's/\//\\\\/'g);
          grep -q -e "\"${win_file}\"" cpp-linear-algebra.vcxproj;
        done
