name: Windows unit tests
description: Build the executable msbuild

on:
  pull_request:
    branches: [ "main" ]

jobs:
  compile_all:
    name: Compile all
    runs-on:  windows-latest
    strategy:
      # Define all combinations you want to build
      matrix:
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd    # v6.0.2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@323ab0502cd38fdc493335025a96c8fdb0edc71f # v2.0.1
    - name: Restore NuGet Packages
      run: nuget restore cpp-linear-algebra.slnx
    # - name: Install Intel Thread Building Block (TBB)
    #   shell: bash
    #   run: |
    #     sudo apt update
    #     sudo apt install libtbb-dev
    - name: ⚒️ Build unit tests
      run: |
        msbuild unit_tests/unit_tests.vcxproj `
        /p:Configuration=${{ matrix.configuration }} `
        /p:Platform=x64 `
        /p:PlatformToolset=v143 `
        /m
    - name: 🧪 Run Google Tests
      run: unit_tests\x64\${{ matrix.configuration }}\unit_tests.exe
