name: Windows build and unit tests (solution file) 👷
description: Build the executable msbuild

on:
  push:
#   pull_request:
#     branches: [ "main" ]

jobs:
  compile_all:
    name: Compile all
    runs-on:  windows-latest
    strategy:
      # Define all combinations you want to build
      matrix:
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2
    # - name: Install Intel Thread Building Block (TBB)
    #   shell: bash
    #   run: |
    #     sudo apt update
    #     sudo apt install libtbb-dev
    - name: Build Solution
      run: |
        msbuild cpp-linear-algebra.slnx `
        /p:Configuration=${{ matrix.configuration }} `
        /p:Platform=${{ matrix.platform }} `
        /m


  test:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8    # v6.0.1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2
    - name: Build Unit Tests
      run: msbuild YourSolution.slnx /p:Configuration=unit /p:Platform=x64
    - name: Run Unit Tests
      run: .\x64\unit\cpp-linear-algebra.exe
